== Developing Cloud-native applications - Appsody

=== Getting to know Appsody

ifdef::include-codewind[]
We are going to start by trying out the developer experience Appsody
provides and then we’ll move on to use Eclipse Codewind.
endif::[]

Let’s take a look at what Appsody provides in terms of capabilities. In
a command prompt, type:

[source, role='command']
```
appsody
```

You should see output similar to the following:

[source, role="no_copy"]
----
The Appsody command-line tool (CLI) enables the rapid development of cloud native applications.

Complete documentation is available at https://appsody.dev

Usage:
  appsody [command]

Available Commands:
  build       Build a local container image of your Appsody project.
  completion  Generate tab completions
  debug       Debug your Appsody project.
  deploy      Build and deploy your Appsody project to Kubernetes.
  extract     Extract your Appsody project to a local directory.
  help        Help about any command
  init        Initialize an Appsody project.
  list        List the available Appsody stacks.
  operator    Install or uninstall the Appsody operator from your Kubernetes cluster.
  ps          List the Appsody containers running in the local Docker environment.
  repo        Manage your Appsody repositories
  run         Run your Appsody project in a containerized development environment.
  stack       Tools to help create and test Appsody stacks
  stop        Stop the local, running Appsody container.
  test        Test your project in the local Appsody environment.
  version     Show the version of the Appsody CLI.

Flags:
      --config string   The absolute path to the Appsody config file. Use this option when you want to specify your own, customized config file (default '$HOME/.appsody/.appsody.yaml')
      --dryrun          Shows the commands that are called by this command, without running them.
  -h, --help            help for appsody
  -v, --verbose         Prints more detailed log output, to the console and to a file in $HOME/.appsody/logs

Use "appsody [command] --help" for more information about a command.
----

The Appsody CLI has several *Commands*. The majority of these
commands are for working with stacks: build, debug, run stop, test, and
extract, list.

Let’s take a look at what stacks we have available by entering:

[source, role='command']
```
appsody list
```

This command lists the available stacks and you should see something
like:

[source, role="no_copy"]
----
REPO        	ID                       	VERSION  	TEMPLATES        	DESCRIPTION                                              
experimental	go-modules               	0.1.0    	*default         	Runtime for Go using Go 1.11+ modules for dependencies   
experimental	java-spring-boot2-liberty	0.1.11   	*default         	Spring Boot on Open Liberty & OpenJ9 using Maven         
experimental	nodejs-functions         	0.2.0    	*simple          	Serverless runtime for Node.js functions                 
experimental	quarkus                  	0.2.3    	*default         	Quarkus runtime for running Java applications            
experimental	rocket                   	0.1.0    	*simple          	Rocket web framework for Rust                            
experimental	rust                     	0.1.6    	*simple          	Runtime for Rust applications                            
experimental	vertx                    	0.1.4    	*default         	Eclipse Vert.x runtime for running Java applications     
*incubator  	java-microprofile        	0.2.24   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
*incubator  	java-openliberty         	0.2.3    	*default         	Open Liberty & OpenJ9 using Maven                        
*incubator  	java-spring-boot2        	0.3.27   	*default, kotlin 	Spring Boot using OpenJ9 and Maven                       
*incubator  	kitura                   	0.2.6    	*default         	Runtime for Kitura applications                          
*incubator  	node-red                 	0.1.2    	*simple          	Node-RED runtime for running flows                       
*incubator  	nodejs                   	0.3.5    	*simple          	Runtime for Node.js applications                         
*incubator  	nodejs-express           	0.4.5    	scaffold, *simple	Express web framework for Node.js                        
*incubator  	nodejs-loopback          	0.2.3    	*scaffold        	LoopBack 4 API Framework for Node.js                     
*incubator  	python-flask             	0.2.2    	*simple          	Flask web Framework for Python                           
*incubator  	starter                  	0.1.2    	*simple          	Runnable starter stack, copy to create a new stack       
*incubator  	swift                    	0.2.5    	*simple          	Appsody runtime for Swift applications
----

You can see that the available stacks cover a large spectrum of programming languages and runtime frameworks.

You can also register new repositories containing stacks created from
the ground up or as clones of the default stacks shipped with Appsody.

To illustrate that point, you can register the Kabanero stack hub entering the following command:

[source, role='command']
```
appsody repo add kabanero https://github.com/kabanero-io/kabanero-stack-hub/releases/latest/download/kabanero-stack-hub-index.yaml

appsody repo list
```

You should see an output similar to this:

[source, role="no_copy"]
----
NAME        	URL                                                                                                     
*incubator  	https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml                         
experimental	https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml                      
kabanero    	https://github.com/kabanero-io/kabanero-stack-hub/releases/latest/download/kabanero-stack-hub-index.yaml
----

`+incubator+` is the location where the appsody project releases its
stacks. The `+*+` indicates that this is the default repository. We can
instruct appsody to set the new kabanero repository as the default repository:

[source, role="no_copy"]
----
appsody repo set-default kabanero

appsody repo list

NAME        	URL                      
*kabanero   	https://github.com/kabanero-io/kabanero-stack-hub/releases/latest/download/kabanero-stack-hub-index.yaml
experimental	https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
incubator   	https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
----



=== Creating a new Project with Appsody

Create a new directory to contain your project and initialize it with a Node.js Express application, entering the following commands on a terminal: 

[source, role='command']
```
mkdir nodejs
cd nodejs

appsody init kabanero/nodejs-express
```

When the initialization completes, you should see something like:

[source, role="no_copy"]
...
[Warning] The stack image does not contain APPSODY_PROJECT_DIR. Using /project
Running command: docker run --rm --entrypoint /bin/bash docker.io/kabanero/nodejs-express:0.2 -c "find /project -type f -name .appsody-init.sh"
Successfully initialized Appsody project with the kabanero/nodejs-express stack and the default template.


ifdef::include-codewind[]
Open up the project in VS Code.

[source, role='command']
code .
endif::[]

Special note for compiled languages, such as Java: To experience the incremental 
update during development you will need an IDE that automatically compiles the source 
files each time they are saved. For instance, Visual Studio Code with the Red Hat
`+Language Support for Java+, Eclipse, and IntelliJ IDEA are all known
to work.

This project template was designed with simplicity in mind, containing only a skeleton Node.js application and Appsody control files:

[source, role="no_copy"]
```
├── .appsody-config.yaml
├── .gitignore
├── .vscode
│   ├── launch.json
│   └── tasks.json
├── app.js
├── package-lock.json
├── package.json
└── test
    └── test.js
```


=== Live coding with Appsody

Let’s start the new application ready to make some edits. Enter the
following command:

[source, role='command']
appsody run

The run command for this stack has been set up to run the application 
with `node` and use hot code updates to reflect code changes made
to the source tree.

After a while you should see output similar to the following:

[source, role="no_copy"]
Running development environment...
Pulling docker image docker.io/kabanero/nodejs-express:0.2
Running command: docker pull docker.io/kabanero/nodejs-express:0.2
...
[Container] Running command:  npm start
[Container] 
[Container] > nodejs-express@0.2.10 start /project
[Container] > node server.js
[Container] 
[Container] [Fri Mar 20 21:01:20 2020] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 5.1.1.202003102146 (Agent Core 4.0.5)
[Container] [Fri Mar 20 21:01:21 2020] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
[Container] App started on PORT 3000


Let’s now make a code change. The Node.js Express stack can dynamically 
update the running application without needing a restart.

First, navigate to the REST application endpoint to confirm that there
are no resources available. Open the following link in your
browser:

http://localhost:3000/resource

You should see an `+Not Found+` response.

Modify the app.js source file to include the extra "/resource" REST path:

[source,nodejs]
----
const app = require('express')()

app.get('/', (req, res) => {
  res.send("Hello from Appsody!");
});

app.get('/resource', (req, res) => {
  res.send("Resource from Appsody!");
});

module.exports.app = app;
----

You should see that upon saving the file, the source code change is detected 
and the application updated:

[source, role="no_copy"]
[Container] Running command:  npm start
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST signal: interrupt
[Container] 
[Container] > nodejs-express@0.2.10 start /project
[Container] > node server.js
[Container] 
[Container] [Fri Mar 20 21:02:46 2020] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 5.1.1.202003102146 (Agent Core 4.0.5)
[Container] [Fri Mar 20 21:02:46 2020] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
[Container] App started on PORT 3000



Now if you browse http://localhost:3000/resource, you should see the message 
`+Resource from Appsody!+` instead of the original `+Not Found+` message 

Try changing the message in `+app.js+`, saving and
refreshing the page. You’ll see it only takes a couple of seconds 
for the change to take effect.

When you’re done, type `+Ctrl-C+` to end the appsody run.

=== Deploying to Kubernetes

You’ve finished writing your code and want to deploy to Kubernetes. The
Kabanero project integrates https://tekton.dev/[Tekton] as a CI/CD pipeline 
for deploying to Kubernetes (including Knative and Istio). This enables you 
to commit your changes to a git repo and have a Tekton pipeline build and
potentially deploy the project.

The setup of Tekton pipelines is a larger tutorial of its own, but application
developers can use the Appsody `+appsody deploy+` command to deploy the application
to a Kubernetes cluster, which allows the developer to verify whether the application
will build and deploy correctly once it reaches a Tekton pipeline.

If you interested in the Tekton pipelines after completing this tutorial, these
are great tutorials covering the subject:

- https://developer.ibm.com/tutorials/knative-build-app-development-with-tekton/[Deploy a Knative application using Tekton Pipelines]
- https://developer.ibm.com/tutorials/make-continuous-delivery-easier-with-tekton-dashboards/[Continuous delivery with Tekton Dashboards example]

Run the deployment command:

[source, role='command']
appsody deploy

At the end of the deploy, you should see an output like this:

[source, role="no_copy"]
Built docker image dev.local/nodejs
Using applicationImage of: dev.local/nodejs
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f app-deploy.yaml --namespace default
Deployment succeeded.
Appsody Deployment name is: nodejs
Running command: kubectl get rt nodejs -o jsonpath="{.status.url}" --namespace default
Attempting to get resource from Kubernetes ...
Running command: kubectl get route nodejs -o jsonpath={.status.ingress[0].host} --namespace default
Attempting to get resource from Kubernetes ...
Running command: kubectl get svc nodejs -o jsonpath=http://{.status.loadBalancer.ingress[0].hostname}:{.spec.ports[0].nodePort} --namespace default
Deployed project running at http://localhost:30062


It is possible you will hit https://github.com/appsody/appsody/issues/764[this issue in Appsody], which incorrectly indicates that the deployment failed:

[source, role="no_copy"]
Running command: kubectl get svc nodejs -o "jsonpath=http://{.status.loadBalancer.ingress[0].hostname}:{.spec.ports[0].nodePort}" --namespace default
[Error] Failed to get deployment hostname and port: Failed to find deployed service IP and Port: kubectl get failed: exit status 1: Error from server (NotFound): services "nodejs" not found
[Error] Failed to find deployed service IP and Port: Failed to find deployed service IP and Port: kubectl get failed: exit status 1: Error from server (NotFound): services "nodejs" not found

If you hit that error, execute this command to get the port number:

[source, role='command']
----
public_port=$(kubectl get service nodejs -o yaml  -o jsonpath='{.spec.ports[0].nodePort}')

echo "http://localhost:${public_port}"
----


The very last line tells you where the application is available. Let’s
call the resource by opening this endpoint in the browser:

http://localhost:30062/resource

You should now see the response from your JAX-RS resource.

Let’s take a look at the deployment. Enter:

[source, role='command']
kubectl get all


You should see an output similar to this:

[source, role="no_copy"]
--
NAME                                    READY   STATUS    RESTARTS   AGE
pod/appsody-operator-5cccdc456b-hs2z9   1/1     Running   0          9m17s
pod/nodejs-7cfd9f478c-sb7x6             1/1     Running   0          9m8s

NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP          8d
service/nodejs       NodePort    10.111.237.25   <none>        3000:32632/TCP   9m8s

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/appsody-operator   1/1     1            1           9m17s
deployment.apps/nodejs             1/1     1            1           9m8s

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/appsody-operator-5cccdc456b   1         1         1       9m17s
replicaset.apps/nodejs-7cfd9f478c             1         1         1       9m8s
--

The entries with `+nodejs+` correspond to Kubernetes resources
created to support your application. The
`+appsody-operator+` resources are those used by Appsody to perform the
deployment.

It is worth noting at this point that this deployment was achieved
without the need for writing or even understanding a Dockerfile or 
Kubernetes deployment file.

Now we can list the files in the project directory, which should contain
files like this:

[source, role="no_copy"]
....
-rw-rw-r--  1 nastacio  staff   4008 Mar 20 17:04 app-deploy.yaml
-rw-r--r--  1 nastacio  staff    209 Mar 20 17:02 app.js
drwxr-xr-x  2 nastacio  staff     64 Mar 20 17:01 node_modules
-rw-r--r--  1 nastacio  staff  51421 Mar 20 16:57 package-lock.json
-rw-r--r--  1 nastacio  staff    455 Mar 20 16:57 package.json
drwxr-xr-x  3 nastacio  staff     96 Mar 20 16:57 test
....

The `+app-deploy.yaml+` is generated from the stack and used to deploy
the application to Kubernetes. If you look inside the file, you will see 
entries for liveness and readiness probes, metrics, and the service port.

Check out the `+live+` and `+ready+` endpoints by pointing your
browser at the following URLs, remembering to replace the port numbers with
the port numbers from the output of the `appsody deploy` command:

* http://localhost:30062/live
* http://localhost:30062/ready

You should see something like:

[source,json]
----
// http://localhost:30062/ready

{
    "status":"UP",
    "checks":[]
}
----

These endpoints are provided by the stack health checks generated
by the project starter.

Finally, let’s undeploy the application by entering:

[source, role='command']
```
appsody deploy delete
```


You should see something like this in the command-line output:

[source, role="no_copy"]
----
....
Deleting deployment using deployment manifest app-deploy.yaml
Attempting to delete resource from Kubernetes...
Running command: kubectl delete -f app-deploy.yaml --namespace default
Deployment deleted
....
----

Check that everything was undeployed using:

[source, role='command']
```
kubectl get all
```

You should see output similar to this:

[source, role="no_copy"]
....
NAME                                    READY   STATUS    RESTARTS   AGE
pod/appsody-operator-5cccdc456b-hs2z9   1/1     Running   0          11m

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   8d

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/appsody-operator   1/1     1            1           11m

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/appsody-operator-5cccdc456b   1         1         1       11m
....

What if you decide you want to see the Container and Kubernetes
configuration that Appsody is using, or you want to take your project
elsewhere? You can do this as follows. Enter:

[source, role='command']
```
appsody extract --target-dir tmp-extract
```

You should see output similar to:

[source, role="no_copy"]
....
Extracting project from development environment
Pulling docker image docker.io/kabanero/nodejs-express:0.2
Running command: docker pull docker.io/kabanero/nodejs-express:0.2
0.2: Pulling from kabanero/nodejs-express
Digest: sha256:e146ec0b008cd122f3c87b50e2d69102141f71dfd44239d1dbaeac97d06737a0
Status: Image is up to date for kabanero/nodejs-express:0.2
docker.io/kabanero/nodejs-express:0.2
[Warning] The stack image does not contain APPSODY_PROJECT_DIR. Using /project
Running command: docker create --name nodejs-extract -v /Users/nastacio/workspace/kabanero-workshop/nodejs/:/project/user-app docker.io/kabanero/nodejs-express:0.2
Running command: docker cp nodejs-extract:/project /Users/nastacio/.appsody/extract/nodejs
Project extracted to /Users/nastacio/workspace/kabanero-workshop/nodejs/tmp-extract
Running command: docker rm nodejs-extract -f
....

Take a look at the extracted project switching to that `tmp-extract` directory. It should contain files similar to the ones in the listing below:

[source, role="no_copy"]
....
drwxr-xr-x   10 nastacio  staff     320 Mar 10 17:46 .
drwxr-xr-x   12 nastacio  staff     384 Mar 20 17:16 ..
-rw-rw-r--    1 nastacio  staff      48 Mar 10 17:45 .dockerignore
-rw-rw-r--    1 nastacio  staff    1075 Mar 10 17:45 Dockerfile
drwxr-xr-x  298 nastacio  staff    9536 Mar 10 17:46 node_modules
-rw-r--r--    1 nastacio  staff  102510 Mar 10 17:46 package-lock.json
-rw-rw-r--    1 nastacio  staff     660 Mar 10 17:45 package.json
-rw-rw-r--    1 nastacio  staff    1462 Mar 10 17:45 server.js
drwxrwxr-x    3 nastacio  staff      96 Mar 10 17:45 test
drwxr-xr-x   11 nastacio  staff     352 Mar 20 17:04 user-app
....


These are the files for the project, including those provided by the
stack. For example, the `+package.json+` has the package dependencies
for your application, and the `+Dockerfile+` is the one used to build and package
the application. The `+user-app+` directory contains the Node.js project for your
application.

ifdef::include-codewind[]
That’s it for the Appsody part of the tutorial.
endif::[]

You have seen how Appsody
`+stacks+` and `+templates+` make it easy to get started with a new
project, using a curated and consistent dev and production environment.

You have also seen how Appsody makes it easier to build
production-ready containers and deploy them to a Kubernetes environment.
