== Working with Kabanero Collections

A collection includes everything you need to create a microservice in a
single container image, along with an enterprise-grade deployment &
integrated continuous delivery choice. Collections are developed by
application architects to match their organizational and product
requirements and work as the basis for applications created by
application developers.

A collection is defined by a combination of a stack (container images
and application templates), build/CD conventions, and deployment
best-practices.

The workshop will cover various aspects of the customization of an
existing collection, which will better prepare you for eventually
creating an entirely new collection after the workshop. 

Kabanero Collections are custom Appsody Stacks and follow the same
development process described in the
https://appsody.dev/docs/stacks/create["Creating a Stack"] section of
the Appsody website, which will be referenced throughout this section. 


=== Stacks

A https://appsody.dev/docs/stacks/stacks-overview[stack] contains at
least one pre-built container image, with the resulting runtime being
tailored to the target runtime. An application architect may to specify
different tunning parameters for a single image, such as dynamic code
reloading for development environments, or provide distinct images for
different purposes, such as an image stripped out of shell support for
production environments.

You can study the internal file structure of a stack in more detail
https://appsody.dev/docs/stacks/stack-structure[here].

=== Workshop custom stack

We are going to use a custom stack created for this workshop. Anybody can
write a stack or customize a stack for use by others. Maybe you want to
add support for another language or framework, or perhaps your company
has additional governance requirements that you want to add into an
existing stack. We’ll go into more details on stack development later,
but for now, let’s add in the stack we’ll use in this part of the
workshop.

The preparation steps for the workshop cloned the Kabanero collections
repository to your local workstation (see snippet of cloning steps below), 
so we can make local modifications and 
use `appsody stack` commands to build the custom versions of collections.

[source, role="no_copy"]
....
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"

[ ! -e "${workshop_dir}/collections" ] && \
( mkdir -p "${workshop_dir}"
  cd "${workshop_dir}"
  git clone https://github.com/kabanero-io/collections )
....


The https://github.com/kabanero-io/collections[Kabanero Collections repository] has the 
complete instructions for releasing the custom collections for usage within a larger 
organization.

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
cd ${workshop_dir}/collections/incubator
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
cd %workshop_dir%\collections\incubator
```
--

If you list the contents of that directory, you should see something like this:

[source, role="no_copy"]
----
common
java-microprofile
java-spring-boot2
nodejs
nodejs-express
nodejs-loopback
triggers
----

This is the list of Kabanero collections, which each directory containing the folder
structure matching the https://appsody.dev/docs/stacks/stack-structure[structure of an Appsody stack].
The stack we want to use is in the `+nodejs-express+` directory.

Let's take a look at the files inside that directory:

[source, role="no_copy"]
....
find . -type f
./stack.yaml
./pipelines/.gitkeep
./image/Dockerfile-stack
./image/LICENSE
./image/config/app-deploy.yaml
./image/project/test/test.js
./image/project/server.js
./image/project/Dockerfile
./image/project/.dockerignore
./image/project/package.json
./image/.dockerignore
./README.md
./templates/simple/test/test.js
./templates/simple/.gitignore
./templates/simple/package-lock.json
./templates/simple/package.json
./templates/simple/.vscode/launch.json
./templates/simple/.vscode/tasks.json
./templates/simple/app.js
./templates/scaffold/test/test.js
./templates/scaffold/.gitignore
./templates/scaffold/package-lock.json
./templates/scaffold/package.json
./templates/scaffold/.vscode/launch.json
./templates/scaffold/.vscode/tasks.json
./templates/scaffold/views/index.pug
./templates/scaffold/routes/index.js
./templates/scaffold/app.js
./collection.yaml
....

The "image" directory defines the base runtime for all templates in the collection,
with the templates for the collection listed as sub-directories of the "templates" directory.

We will be working with the "simple" template.

=== Building the custom stack

The commands for developing custom stacks are bundled under the `appsody stack` command:

[source, role='command']
```
appsody stack --help
```

[source, role="no_copy"]
....
Tools to help create and test Appsody stacks

Usage:
  appsody stack [command]

Available Commands:
  lint        Lint your stack to verify that it conforms to the standard of an Appsody stack
  package     Package a stack in the local Appsody environment
  validate    Run validation tests of a stack in the local Appsody environment
....

We want to use the `package` sub-command to generate a local copy of the stack:

[source, role='command']
```
cd nodejs-express
appsody stack package
```


You will notice the presence of the new dev.local repository:

[source, role='command']
```
appsody repo list
```

You should see:

[source, role="no_copy"]
----
*kabanero           	https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml           
dev.local           	file:///Users/nastacio/.appsody/stacks/dev.local/dev.local-index.yaml                             
experimental        	https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml                
incubator           	https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml                   
----

Let’s see what stacks we now have available:

[source, role='command']
```
appsody list
```

You should now see an entry for a stack called
`+nodejs-express+` from the `+dev.local+` repository.

[source, role="no_copy"]
--
REPO                	ID                       	VERSION  	TEMPLATES        	DESCRIPTION                                              
dev.local           	nodejs-express           	0.2.8    	scaffold, *simple	Express web framework for Node.js                        
experimental        	java-spring-boot2-liberty	0.1.11   	*default         	Spring Boot on Open Liberty & OpenJ9 using Maven         
experimental        	nodejs-functions         	0.1.6    	*simple          	Serverless runtime for Node.js functions                 
experimental        	quarkus                  	0.2.2    	*default         	Quarkus runtime for running Java applications            
experimental        	rocket                   	0.1.0    	*simple          	Rocket web framework for Rust                            
experimental        	rust                     	0.1.4    	*simple          	Runtime for Rust applications                            
experimental        	vertx                    	0.1.4    	*default         	Eclipse Vert.x runtime for running Java applications     
incubator           	java-microprofile        	0.2.21   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
incubator           	java-spring-boot2        	0.3.19   	*default, kotlin 	Spring Boot using OpenJ9 and Maven                       
incubator           	kitura                   	0.2.3    	*default         	Runtime for Kitura applications                          
incubator           	nodejs                   	0.2.5    	*simple          	Runtime for Node.js applications                         
incubator           	nodejs-express           	0.2.10   	scaffold, *simple	Express web framework for Node.js                        
incubator           	nodejs-loopback          	0.1.8    	*scaffold        	LoopBack 4 API Framework for Node.js                     
incubator           	python-flask             	0.1.6    	*simple          	Flask web Framework for Python                           
incubator           	starter                  	0.1.1    	*simple          	Runnable starter stack, copy to create a new stack       
incubator           	swift                    	0.2.3    	*simple          	Appsody runtime for Swift applications                   
*kabanero           	java-microprofile        	0.2.19   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
*kabanero           	java-spring-boot2        	0.3.18   	*default, kotlin 	Spring Boot using OpenJ9 and Maven                       
*kabanero           	nodejs                   	0.2.6    	*simple          	Runtime for Node.js applications                         
*kabanero           	nodejs-express           	0.2.8    	scaffold, *simple	Express web framework for Node.js                        
*kabanero           	nodejs-loopback          	0.1.6    	*scaffold        	LoopBack 4 API Framework for Node.js                     
--

We are now ready to start customizing this local stack and creating sample applications 
to test its functionality.


=== Collection Scenario 1: Update the release of Node.js express in the stack

In this scenario, a new version of Node.js `express` is released and you, as the application
architect, want all applications based on this stack to be migrated to
the latest release in the next development and deployment cycle.

The first step is to clone the stack, which was already executed by the
prerequisite preparation steps.


In this stack, the file `./image/project/package.json` specifies the version 
of `express`.

You now modify that version "~4.16.0" to work with the newer minor version "~4.17.0":

[source,json]
----
{
  "name": "nodejs-express",
  "version": "0.2.6",
  "description": "Node.js Express Stack",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/appsody/stacks.git",
    "directory": "incubator/nodejs-express/image/project"
  },
  "scripts": {
    "debug": "node --inspect=0.0.0.0 server.js",
    "start": "node server.js",
    "test": "mocha"
  },
  "dependencies": {
    "@cloudnative/health-connect": "^2.0.0",
    "appmetrics-prometheus": "^3.0.0",
    "express": "~4.17.0"   // <1>
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "mocha": "~6.1.0",
    "request": "^2.88.0",
    "appmetrics-dash": "^5.0.0"
  }
}
----
<1> Newer `express` framework version

With the version changed, we need to rebuild the stack before proceeding
with the stack validation steps.

[source, role='command']
....
appsody stack package
....

As an optimization step, since all Docker images being generated for this local
stack are not located in a remote repository, we can save time by informing
Appsody to not download images that are already in the local repository:

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
export APPSODY_PULL_POLICY=IFNOTPRESENT
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set APPSODY_PULL_POLICY=IFNOTPRESENT
```
--

It is now time to verify the changes from the perspective of the
application developer. We can go back to the original application
directory and trigger another run, which will use the updated stack:

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
mkdir -p "${workshop_dir}/nodejs-local"
cd "${workshop_dir}/nodejs-local"

appsody init dev.local/nodejs-express
appsody run
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
mkdir "%workshop_dir%\nodejs-local"
cd "%workshop_dir%\nodejs-local"

appsody init dev.local/nodejs-express
appsody run
```
--

Once the application is running, we can open a different terminal window and use 
a `docker exec` command to inspect the content of the package.json for the application 
and verify that the `express` framework version now reflects the new value placed in 
the stack:

[source, role='command']
```
docker exec -it nodejs-local-dev /bin/sh -c "cat package.json"
```

[source, role="no_copy"]
....
{
  ...
  "dependencies": {
    "@cloudnative/health-connect": "^2.0.0",
    "appmetrics-prometheus": "^3.0.0",
    "express": "~4.17.0"    <<<<<<< new express version in the stack
  }
  ...
}
....

End the application with `+Ctrl+C+`.

=== Collection Scenario 2: Custom application template

A stack contains at least one application template, which is the set of
application files placed in the application directory during the initial
creation of a project. The default template for a stack is defined in
stack.yaml file in the stack directory and  used by
`+appsody init+` when the user does not specify a template name.

For instance, for the nodejs-express stack, we can see the following content
for stack.yaml:

[source, role="no_copy"]
....
name: Node.js Express
version: 0.2.6
description: Express web framework for Node.js
license: Apache-2.0
language: nodejs
...
default-template: simple  <<<<<
....


An application architect can create new templates to reflect different
starting points for application developers, such as a default template
for a simple stateless application or a more complex template with
starter code for connecting to a remote database.

In this scenario, we will inspect an alternative template with a
PostgreSQL database connection endpoint, then create and test an
application starter using that template.

We first need to create the alternative template, which will be based
on the "simple" template:

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
cd "${workshop_dir}/collections/incubator/nodejs-express/templates"
cp -rf simple psqldb

```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
cd "%workshop_dir%\collections\incubator\nodejs-express/templates"
copy /s simple psqldb
```
--

The next step is to modify the "package.json" file for the template 
to include the PostgreSQL dependency, which is in the new "psqldb" directory
created in the previous step:


[source, role='command']
```
cd psqldb
```

Insert the new line for "pg-promise" in the package.json file, 
inside the "devDependencies" block, as follows:

[source, role="no_copy"]
.package.json
[source, json, linenums, role='code_column hide_tags=copyright,fallback,fallbackMethod']
----
include::collections/incubator/nodejs-express/templates/psqldb/package.json[]
----

The next step is to show how the template code could have a small sample
of database connectivity. Notice we are hardcoding the database connectivity
parameters in the interest of simplicity, but in a real application these
values should be provided through an external mechanism, such as Docker 
environment variables (`appsody run --docker-options="-e ..."`) or, later
in production, through secrets bound to the Kubernetes deployment or pod.

Modify the `app.js` code inside the newly created "psqldb" directory to 
look like the content below:

app.js
[source, javascript, role='code_column hide_tags=copyright,fallback,fallbackMethod']
----
include::collections/incubator/nodejs-express/templates/psqldb/app.js[]
----

We are now ready to re-build our collection to include the new template:

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
cd "${workshop_dir}/collections/incubator/nodejs-express"

appsody stack package
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
cd "%workshop_dir%\collections\incubator\nodejs-express"

appsody stack package
```
--

We can now see the new template next to the other templates in the nodejs-express
stack:

[source, role='command']
```
appsody list dev.local
```

Which should show the following output, where you notice the new "psqldb" template
in the "TEMPLATES" column:

[source, role="no_copy"]
....
REPO     	ID            	VERSION  	TEMPLATES                	DESCRIPTION                      
dev.local	nodejs-express	0.2.6    	psqldb, *simple, skaffold	Express web framework for Node.js
....

Before testing our application, our next step is to instantiate a local PostgreSQL database. We will use a custom docker network for both the PostgreSQL database container and the application container, which makes it easier for the application container to locate the database container by hostname instead of IP address.

[source, role='command']
```
docker network create workshop_nw

docker run --rm -it --name workshop-postgres --hostname psqldb --network workshop_nw -e POSTGRES_PASSWORD=mysecretpassword -d postgres 
```

Ensure the database container is running:

[source, role='command']
```
docker ps

b66c53a3be0f        postgres                                                  "docker-entrypoint.s…"   22 seconds ago      Up 21 seconds       5432/tcp                    workshop-postgres
```

Now we can create a new application, using the template containing the
database resource:


[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
mkdir -p "${workshop_dir}/nodejs-db"
cd "${workshop_dir}/nodejs-db"
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
mkdir "%workshop_dir%\nodejs-db"
cd "%workshop_dir%\nodejs-db"
```
--


All users:

....
appsody init dev.local/nodejs-express psqldb

appsody run --network workshop_nw
....

Wait for the application to complete its startup cycle and verify that
the new endpoint is available, by opening the
http://localhost:3000/database/ URL in a web browser, where you
should shee output like this:

....
PostgreSQL 12.0 (Debian 12.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
....

End the application with `+Ctrl+C+`, stop the workshop-postgres
container, and delete the custom network:

[source, role='command']
```
docker stop workshop-postgres
docker network rm workshop_nw
```

=== Build/CD

A collection also specifies how applications should be built and
packaged, encoding conventions about compilation aspects, packaging
tooling, unit test enforcement, static code analysis, and many others. A
full Kabanero toolchain is implemented as a sequence of steps that
happen both inside and outside the container boundaries, and this
workshop covers the steps that happen within the container boundaries,
such as compilation and packaging of binaries.

This portion of the instructions is executed directly when the developer
invokes `+appsody build+` or implicitly, when the developer invokes
`+appsody deploy+` and there are outstanding code changes since the last
build.

=== Collection Scenario 3: Add static code verification to build process

In this scenario, the entire team discussed ways of making code reviews
more efficient and agreed on ensuring minimal coding guidelines for all
applications based on that stack.

After considering multiple tools, the team agreed on using
https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html[eslint]
, and the application architect can make that modification to the stack
image itself.

For simplicity we will use the default eslint rules, so that we need to
add an appropriate eslint configuration file in the image and invoke 
`eslint` in the application code.

Locate the Dockerfile for the stack:

....
${workshop_dir}/collections/incubator/nodejs-express/image/project/Dockerfile
....

And introduce the following lines right before the line containing
`WORKDIR /project`

[source, role="no_copy"]
----
RUN chown -hR node:node /project

# ESLint invocation
RUN npm install eslint \
    && echo 'module.exports = { \
    "env": { \
        "browser": false, \
        "commonjs": true, \
        "es6": true \
    }, \
    "extends": "eslint:recommended", \
    "globals": { \
        "Atomics": "readonly", \
        "SharedArrayBuffer": "readonly" \
    }, \
    "parserOptions": { \
        "ecmaVersion": 2018 \
    }, \
    "rules": { \
      "no-empty": "warn" \
    } \
};' > .eslintrc.js \
    && echo 'test/*' >  .eslintignore \
    && ./node_modules/.bin/eslint /project/user-app

WORKDIR /project
----

With the change in place, we can rebuild the stack again.


[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
cd "${workshop_dir}/collections/incubator/nodejs-express"

appsody stack package 
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
cd "%workshop_dir%\collections\incubator\nodejs-express"

appsody stack package 
```
--

With the code verification in place, we are almost ready to see the new code 
verification step in action when an application developer executes `+appsody build+`:

First we create a source file inside the `nodejs-local` project, with a violation 
to the default rule against empty blocks, named app-rule-violation.js

[source, js]
```
var a=1
if (a) {
}
```

[.tab_link.mac_link]
`*MAC*`

[.tab_link.windows_link]
`*WINDOWS*`

[.tab_content.mac_section]
--
[source, role='command']
```
workshop_dir=$(echo ~)"/workspace/kabanero-workshop"
cd "${workshop_dir}/nodejs-local"

appsody build
```
--

[.tab_content.windows_section]
--
[source, role='command']
```
set workshop_dir="%USERPROFILE%\workspace\kabanero-workshop"
cd "%workshop_dir%\nodejs-local"

appsody build
```

Eventually you will see the following log snipped pass by, indicating
the new checks during build time: 

--

[source, role="no_copy"]
----
...
[Docker]  ---> Running in 0b8bf6444ceb
[Docker] + eslint@6.6.0
[Docker] added 126 packages from 560 contributors, updated 1 package and audited 474 packages in 6.615s
[Docker] found 0 vulnerabilities
[Docker] 
[Docker] 
[Docker] /project/user-app/app-rule-violation.js
[Docker]   2:8  warning  Empty block statement  no-empty
[Docker] 
[Docker] ✖ 1 problem (0 errors, 1 warning)
[Docker] 
...
----


=== Collection Scenario 4: Stack versioning

Appsody supports https://semver.org/[semantic versioning] during
development of stacks and applications. Notice how the check from the previous 
scenario does not fail the build process, but instead prints a summary of warnings 
for the developer.

This decision was done by design, as an application architect may want
to give some time for the whole team to address the issues raised by the 
static code analysis without suddenly disrupting their workflow.

In this scenario, we want to show how the application architect could
release a new version of the stack that will treat the warnings as blocking
errors, but will not automatically get picked up by developers immediately 
after release, so we need to understand how Appsody tags stack images.

The initial version of the stack used in this workshop is 0.2.*, which
is listed in the output of `+appsody list+`. 

[source, role="no_copy"]
--
appsody list dev.local 

REPO     	ID            	VERSION  	TEMPLATES                	DESCRIPTION                                         
dev.local	nodejs-express	0.2.7    	psqldb, scaffold, *simple	Express web framework for Node.js          
--

Locate the stack metadata file for the stack;

....
${workshop_dir}/collections/incubator/nodejs-express/stack.yaml
....


Now modify the version of the stack in "stack.yaml" to replace the "version" field
with 0.3.0, so that the final file looks like this:

[source]
----
name: Node.js Express
version: 0.3.0
description: Express web framework for Node.js
...
default-template: simple
----

Locate the Dockerfile for the stack:

....
${workshop_dir}/collections/incubator/nodejs-express/image/project/Dockerfile
....

Modify the line with the definition for the rule "no-empty" to 
be treated as an error:

[source, role="no_copy"]
----
...
    "rules": { \
      "no-empty": "error" \
    } \
...
----

We can now proceed to package and tag the modified stack:

[source, role='command']
```
appsody stack package
docker tag dev.local/nodejs-express:SNAPSHOT dev.local/nodejs-express:0.3
```


With the the new stack updated and packaged, we can turn back to the
application and modify

Locate the directory for the application being used to test the stack;
....
${workshop_dir}/nodejs-local
....

Modify the file named `.appsody-config.yaml` to use the new stack
version. The final file contents should look like this:

[source, role="no_copy"]
----
project-name: nodejs-local
stack: dev.local/nodejs-express:0.3
----

We can now build the application using the updated stack and observe the
new behavior, where the rule violation causes the build to break.

[source, role="no_copy"]
----
[Docker] + eslint@6.6.0
[Docker] added 126 packages from 560 contributors, updated 1 package and audited 474 packages in 6.33s
[Docker] found 0 vulnerabilities
[Docker] 
[Docker] 
[Docker] /project/user-app/app-rule-violation.js
[Docker]   2:8  error  Empty block statement  no-empty
[Docker] 
[Docker] ✖ 1 problem (1 error, 0 warnings)
[Docker] 
[Docker] The command '/bin/sh -c npm install eslint     && echo 'module.exports = {     "env": {         "browser": false,         "commonjs": true,         "es6": true     },     "extends": "eslint:recommended",     "globals": {         "Atomics": "readonly",         "SharedArrayBuffer": "readonly"     },     "parserOptions": {         "ecmaVersion": 2018     },     "rules": {       "no-empty": "error"     } };' > .eslintrc.js     && echo 'test/*' >  .eslintignore     && ./node_modules/.bin/eslint /project/user-app' returned a non-zero code: 1
[Error] exit status 1
----

At this point, developers still using the previous version would be notified 
to ensure all errors are fixed before updating the `.appsody-config.yaml` 
for their application, probably receiving some grace period until the previous 
stack is discontinued.

=== Further reading: Development versus production behaviour

The previous scenarios showed relatively simple changes, but Kabanero collections
can accommodate more sophisticated behaviours, where the container image
is setup with additional debugging capabilitites during development and
stripped out of those capabilities during production.

You can read more about deciding on whether to create new stacks or
modify existing stacks in https://developer.ibm.com/articles/customizing-appsody/[this article].
If you decide to create a new stack, https://developer.ibm.com/tutorials/create-appsody-stack/[this tutorial] 
has excellent guidance for that activity.

This
https://github.com/appsody/stacks/pull/56[Git pull request] shows how
that type of different behaviour can be achieved, by exploring the usage
of https://appsody.dev/docs/stacks/stack-structure[different modes of a
stack]: "initialization", "rapid local development", and "build and
deploy".
