---
permalink: /guides/dev-getting-started/
---
:projectid: dev-getting-started
:page-layout: guide
:page-duration: 75 minutes
:page-description: Workshop content for developers and solution architects getting started with Kabanero
:page-tags: ['Appsody', 'Nodejs', 'Express']
:page-title: Getting Started With Kabanero Development
:linkattrs:

:kabanero-collection: v0.2.0
:include-codewind: true

= Getting Started With Development for Project Kabanero

include::whatis.adoc[]

== What you will learn

This tutorial is split into two parts, giving you an introduction to 
the developer experience, as well as an introduction to the 
solution architecture portion of its unified experince.

In the developer experience, you will be creating and deploying a 
cloud-native microservice, leveraging a pre-existing application template 
and runtime stack along the way.

In the solution architecture portion, you will modify and extend the 
application template and stack, observing how those changes reflect
automatically into applications created in the first portion.

At the end of this tutorial, you should have a good understanding of the
developer experience through the use of the https://appsody.dev[Appsody]
command-line interface, productive code iterations through the usage of 
https://www.eclipse.org/codewind/[Codewind], as well as basic notions
of how to play the role of a solution architect creating application stacks
for your organizaton.

Note that the tutorial is based on a Node.js application using the 
https://expressjs.com/[Express] framework, but the applications stacks
also include support for other programming languages and frameworks, and 
the platform supports the modular addition of support for other languages 
and frameworks through the creation of 
https://appsody.dev/docs/stacks/stacks-overview[application stacks].


include::prerequisites-raw.adoc[]

include::appsody.adoc[]

ifdef::include-codewind[]
Let’s now take a look at Codewind.

include::codewind.adoc[]
endif::[]

include::stacks.adoc[]

